repos:
- repo: local
  hooks:
  - id: black
    name: black
    language: system
    entry: black creative_project/ --check
    types: [python]

  - id: isort
    name: isort
    language: system
    entry: isort creative_project/**/*.py --check-only
    types: [python]