# deployment workflow to test-PyPI

name: Publish python package greattunes to TestPyPI

on:
  push:
    branches:
      - staging

jobs:
  run-example-notebooks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  # does this take the code from master of repo?
        with:
          ref: 'staging'
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies for running notebooks
        run: |
          pip install --upgrade jupyter nbconvert ipython
          # pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
          pip install -r requirements.txt
          pip install -e .  # install greattunes from checked-out code
      - name: Run notebooks
        run: for FILE in examples/*.ipynb; do jupyter nbconvert --to notebook --execute "$FILE"; done
          #jupyter nbconvert --to notebook --execute examples/*.ipynb
          # identify all notebooks in folder
          #import os
          #homepath = os.getcwd()
          #nbpath = os.path.join(homepath, "examples")
          #notebooks = [f for f in os.listdir(nbpath) if "ipynb" in f]
          ## run notebooks
          #for i in range(len(notebooks)):
          #  nb = os.path.join(nbpath,notebooks[i])
          #  fn = nb[:-5] + "py"
          #  os.system(f"jupyter nbconvert --to script {nb}")  # convert to python script
          #  os.system("python {fn}")
        continue-on-error: false

  build-n-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install build dependencies
        run: |
          pip install --upgrade setuptools wheel
          pip install --upgrade -r requirements.txt
      - name: Build package
        run: python3 setup.py bdist_wheel
      - name: Publish distribution of greattunes to TestPyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TESTPYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
