# deployment workflow to test-PyPI

name: Publish python package greattunes to TestPyPI

on:
  push:
    branches:
      - staging

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build package
        run: python3 setup.py bdist_wheel
      - name: Publish distribution of greattunes to TestPyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TESTPYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
